-- MySQL Script generated by MySQL Workbench
-- Wed Aug 25 03:34:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema guest_book
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema guest_book
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `guest_book` DEFAULT CHARACTER SET utf8 ;
USE `guest_book` ;

-- -----------------------------------------------------
-- Table `guest_book`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guest_book`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guest_book`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guest_book`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `image` VARCHAR(250) NULL,
  `price` FLOAT NULL,
  `available` TINYINT NULL,
  `userid` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `userdata_idx` (`userid` ASC),
  CONSTRAINT `userdata`
    FOREIGN KEY (`userid`)
    REFERENCES `guest_book`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guest_book`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guest_book`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
